### ISSUE TITLE
Create Flask endpoints

### ISSUE THREAD

**Issue by APoulad** [jwizenfeld04/Real-Estate-AVM#5]
These endpoints are defined in the detailed workplan as the following:
##### `get_image` (GET):

**Functionality**: Fetch a random property image from GCP Storage that hasn’t been labeled yet. Mark the image as "served" in Firestore to avoid duplicates.

**Implementation**:

- Query GCP Firestore for images where `served = False`.
- Retrieve a random image from GCP Storage using the `image_path` stored in Firestore.
- Set the `served` field to `True` to ensure no other users are served the same image.

**Notes**: Handle cases where no unlabeled images are available.

---

##### `start_session` (POST):

**Functionality**: Initialize a new user session with a username and session type (room labeling or score labeling).

**Implementation**:

- Store session information in Firestore, including `username`, `session type`, and the timestamp when the session starts.

**Notes**: The session data should also track which images have been labeled in the session based on the `image_path/id`.

---

##### `update_label` (POST):

**Functionality**: Update Firestore with the room type or score for a specific image, set the image’s labeled status to `True`, and increment the session score.

**Implementation**:

- Receive the labeled image ID, room type/score, and session information.
- Update the Firestore document associated with the image with the room type or score.
- Increment the user’s session score in Firestore.

**Room Types**:

- Exterior, Bathroom, Bedroom, Kitchen, Living Room, Basement, Attic, Garage, Other.

**Scores**: A scale from 1-9. (Descriptions for each score will be added later).

**Notes**: Ensure robust error handling and validation for input data.

---

##### `reset_image_served` (GET):

**Functionality**: Reset any images that have been served but not labeled after a defined time period (stale images).

**Implementation**:

- Query Firestore for images with `served = True` and `labeled = False`.
- Reset `served = False` for these images, allowing them to be re-served to new users.

**Scheduler**: This endpoint should run periodically using a cloud scheduler (e.g., Cloud Scheduler) to prevent stale images.

---

##### `get_leaderboard` (GET):

**Functionality**: Retrieve a leaderboard of user session scores, sorted by the number of labeled images.

**Implementation**:

- Query Firestore for all user sessions and their scores.
- Return a sorted list of users with the highest labeling scores.

---

##### `skip_image` (POST):

**Functionality**: Allows users to skip an image and reset its served status to `False`.

**Implementation**:

- Receive the image ID and session information.
- Update the Firestore document to reset `served = False`.

**Comment by harishjr16-12** [comment]
Hi , i would like to make contributions in create endpoints feature is there any  maintainer already assigned for that
